Update TheHarvester

diff --git a/TheHarvester b/TheHarvester
--- a/TheHarvester
+++ b/TheHarvester
@@ -1,16 +1,31 @@
 #!/bin/bash
 
 # Clonamos el repositorio de TheHarvester
-cd Descargas
 git clone https://github.com/laramies/theHarvester.git
 cd theHarvester
 
 # Instalamos las dependencias de Python de TheHarvester
-sudo apt-get install python3 python3-pip python3-setuptools
-sudo pip3 install -r requirements/base.txt
+sudo pacman -S python python-pip python-setuptools
+sudo pip install -r requirements/base.txt
 
 # Instalamos TheHarvester
-sudo python3 setup.py install > /tmp/theHarvester.log 2>&1
+sudo python setup.py install > /tmp/theHarvester.log 2>&1
 if [ $? -ne 0 ]; then
   echo "Error: TheHarvester no se pudo instalar correctamente. Por favor revise /tmp/theHarvester.log para más detalles."
 fi
+
+# Clonamos el repositorio de Shodan
+git clone https://github.com/achillean/shodan-python.git
+cd shodan-python
+
+# Instalamos Shodan
+sudo python setup.py install > /tmp/shodan.log 2>&1
+if [ $? -ne 0 ]; then
+  echo "Error: Shodan no se pudo instalar correctamente. Por favor revise /tmp/shodan.log para más detalles."
+fi
+
+# Instalamos Maltego
+sudo pacman -Syy
+wget https://www.paterva.com/malv42/community/MaltegoCE.v4.2.13.13462.deb
+sudo pacman -S gdebi
+sudo gdebi -n MaltegoCE.v4.2.13.13462.deb
